from wx.lib.newevent import NewEvent as NewEvt

#NAV
NavigationEvent, EVT_NAVIGATION = NewEvt()
SelectDogEvent, EVT_SELECT_DOG = NewEvt()
AddDogEvent, EVT_ADD_DOG = NewEvt()
NavDataPass, EVT_NAV_DATA_PASS = NewEvt()
OpenDogPageEvent, EVT_OPEN_DOG_PAGE = NewEvt()
PassDataForDogPageEvent, EVT_PASS_DATA_DOG_PAGE = NewEvt()
OpenGenotypeViewEvent, EVT_VIEW_GENOTYPE = NewEvt()
PassDataForViewGenotype, EVT_VIEWGEN_DATAPASS = NewEvt()
PassFormattedGenotype, EVT_FORMATTEDGEN_DATAPASS = NewEvt()
EditLocusEvent, EVT_EDIT_LOCUS = NewEvt()
OpenEditLocusEvent, EVT_OPEN_EDIT_LOCUS = NewEvt()
PassGenotypeDataEvent, EVT_PASS_GENOTYPE = NewEvt()
PassEditLocusDataEvent, EVT_PASS_EDIT_LOCUS_DATA = NewEvt()
OpenMainMenu, EVT_MAIN_MENU = NewEvt()
OpenAddGoalPanel, EVT_OPEN_ADD_GOAL = NewEvt()
AddGoalEvent, EVT_ADD_GOAL = NewEvt()
DeleteGoalEvent, EVT_DELETE_GOAL = NewEvt()
PassGoalEvent, EVT_PASS_GOAL = NewEvt()
RequestAllGoalsEvent, EVT_REQUEST_ALL_GOALS = NewEvt()
ReturnToBreedingFromGoal, EVT_BREEDING_RETURN = NewEvt()

#SAVE/LOAD
SaveEvent, EVT_SAVE = NewEvt()
LoadEvent, EVT_LOAD = NewEvt()
LoadDogFromDataEvent, EVT_LOAD_DOG_FROM_DATA = NewEvt()
PassDogToDataLayerEvent, EVT_PASS_DOG = NewEvt()
PassDogDataEvent, EVT_PASS_DOG_DATA = NewEvt()
DisplayAllDogsEvent, EVT_DISPLAY_ALL_DOGS = NewEvt()
RequestDogByID, EVT_REQUEST_DOG_BY_ID = NewEvt()
RequestGenotypeByID, EVT_REQUEST_GENOTYPE_BY_ID = NewEvt()
RequestDogs, EVT_REQUEST_DOGS = NewEvt()
PassDogs, EVT_PASS_DOGS = NewEvt()
PassSelectedParentDataEvent, EVT_PASS_SELECTED_PARENT_DATA = NewEvt()
PassDataEvent, EVT_PASS_DATA = NewEvt()
PassGoalsForDisplay, EVT_DISPLAY_GOALS = NewEvt()

#BREEDING
BeginBreedingCalculation, EVT_BEGIN_BREEDCALC = NewEvt()
DoBreedingCalculation, EVT_DO_BREEDCALC = NewEvt()
AddBreedingResult, EVT_ADD_BREEDING_RES = NewEvt()
ViewBreedingResult, EVT_VIEW_BREEDING_RESULT = NewEvt()
OpenBreedingPageEvent, EVT_OPEN_BREEDING_RESULT = NewEvt()
RequestAllBreedingsEvent, EVT_REQUEST_ALL_BREEDINGS = NewEvt()
LoadAllBreedings, EVT_LOAD_ALL_BREEDINGS = NewEvt()
LoadAllDogs, EVT_LOAD_ALL_DOGS = NewEvt()

#DOG EVENTS
DogIncorrectGenotypeEvent, EVT_INCORRECT_GENOTYPE = NewEvt()
DogGenotypeChangedEvent, EVT_GENOTYPE_CHANGED = NewEvt()
ParentSelectedEvent, EVT_PARENT_SELECTED = NewEvt()
PotentialRelativeSelectedEvent, EVT_RELATIVE_SELECTED = NewEvt()
AddRelativeEvent, EVT_ADD_RELATIVE = NewEvt()
AddRelativeLogicEvent, EVT_ADD_RELATIVE_LOGIC = NewEvt()
