TEXT_ABOUT = "About"
INFO_ABOUT = "Information about this program"
TEXT_EXIT = "Exit"
INFO_EXIT = "Exit the program"

# Default panel
TEXT_MYDOGS = "My Dogs"
TEXT_MYBREEDINGS = "My Breedings"
TEXT_BREEDINGCALC = "Breeding Calculator"
TEXT_MYGOALS = "My Breeding Goals"

# Dog page
TEXT_NAMEBARE = "Name"
TEXT_SEX = "Sex: "
TEXT_AGE = "Age: "
TEXT_BREED = "Breed: "
TEXT_COAT = "Coat: "
TEXT_VIEWGENOTYPE = "View Genotype"
TEXT_BREEDINGTESTS = "Breeding Tests"
TEXT_RELATIVES = "Relatives"
TEXT_ADDRELATIVE = "Add Relative"
TEXT_BREEDINGTESTRESULTS = "Breeding Test Results"
TEXT_PREVDOG = "Previous Dog"
TEXT_NEXTDOG = "Next Dog"

# Breeding Panel
TEXT_BREEDINGTYPE = "Breeding Type"
TEXT_CONV = "Conventional"
TEXT_PICKMATE = "Pick best mate"
TEXT_PICKPAIR = "Pick best pair"
TEXT_CREATE = "Create best mate"
TEXT_DAM = "Dam"
TEXT_SIRE = "Sire"
TEXT_SELECT = "Select"
TEXT_GOALS = "Breeding Goals"
TEXT_ADD = "Add"
TEXT_SAVE = "Save"
TEXT_LOAD = "Load"
TEXT_CLEAR = "Clear"
TEXT_CALCULATE = "Calculate"
TEXT_REFRESH = "Refresh"

# Breeding result
TEXT_CLOSE = "Close"
TEXT_CONVRESULTS = "Conventional Breeding Results"
TEXT_POSSIBLECOATS = "Possible Coats"
TEXT_IMPOSSIBLECOATS = "Impossible Coats"
TEXT_PICKMATERESULTS = "Pick Best Mate Breeding Test Results"
TEXT_BESTMATE = "Best Mate"
TEXT_PICKPAIRRESULTS = "Pick Best Pair Breeding Test Results"
TEXT_BESTPAIR = "Best Pair"
TEXT_CREATERESULTS = "Create Best Mate Breeding Test Results"
TEXT_SAVETOMYDOGS = "Save to My Dogs"

# dog select dialog
TEXT_SELECTDOG = "Select Dog"
TEXT_CANCEL = "Cancel"

#add dog dialog
TEXT_AGEBARE = "Age (years)"
TEXT_SEXBARE = "Sex"
TEXT_COATBARE = "Coat"
TEXT_MALE = "Male"
TEXT_FEMALE="Female"
TEXT_IDONTKNOW = "I don't know"

#phens
TEXT_SABLE = "Sable"
TEXT_AGOUTI = "Agouti"
TEXT_TANPOINT = "Tan points"
TEXT_BRINDLE = "Brindle"
TEXT_SOLID_EUMELANIN = "Solid color"
TEXT_SOLID_PHEOMELANIN = "Solid color"
TEXT_MASK = "Masked"
TEXT_NO_MERLE = "No merle"
TEXT_MERLE = "Merle"
TEXT_DOUBLE_MERLE = "Double merle"
TEXT_NO_WHITE = "No white spotting"
TEXT_MINOR_WHITE = "Little white spotting"
TEXT_PIEBALD = "Piebald white pattern"
TEXT_IRISH_WHITE = "Irish white pattern"
TEXT_NO_TICKING = "No ticking/roaning"
TEXT_MINOR_TICKING = "Minor ticking"
TEXT_TICKING = "Ticking"
TEXT_ROANING = "Roaning"
TEXT_GREYING = "Greying"
TEXT_BLACK = "Black"
TEXT_LIVER = "Liver"
TEXT_BLUE = "Blue"
TEXT_ISABELLA = "Isabella"
TEXT_RED = "Red"
TEXT_DILUTE_RED = "Fawn/cream/silver/white"
TEXT_WHITE = "White"

TEXT_INCORRECT_GENOTYPE = """The genotype of this dog is contradictory. Check if the options selected are correct and try again."""
TEXT_WARNING = "Warning!"
TEXT_EDIT = "Edit"
TEXT_CHANGE_ALLELE = "Change Allele at Locus "
TEXT_TYPE = "Type"
TEXT_ALLELE = "Allele"
TEXT_NOTALLELE = "Not Allele"
TEXT_ANYALLELE = "Any Allele"
TEXT_VALUE = "Value"
TEXT_NOT_VALUE = "Not Value"
TEXT_BACK = "Back"